# Work mode for util
## when it's in read_only mode - it just can show current state in HTML according to cp_response settings
## when it isn't in read_only - it also will perform all actions related to alerts
read_only: false

### Params checking rate
check_freq_when_on_batt: 5 # Seconds
check_freq_when_on_line: 10 # Seconds

# List of values
## Not so smart, but more flexible solution just in case of any utility updates or
## possible specific requirements (e.g. shorter description)
##
## "name" field is case-insensitive
cp_response:
  - name: "modelname"
    prettyName: "Model name"
    isShown: true
  - name: "firmwarenumber"
    prettyName: "Firmware number"
    isShown: true
  - name: "ratingvoltage"
    prettyName: "Rating voltage"
    isShown: true
  - name: "ratingpower"
    prettyName: "Rating power"
    isShown: true
  - name: "state"
    prettyName: "State"
    isShown: true
  - name: "powersupplyby"
    prettyName: "Power supply by"
    isShown: true
  - name: "utilityvoltage"
    prettyName: "Utility voltage"
    isShown: true
  - name: "outputvoltage"
    prettyName: "Output voltage"
    isShown: true
  - name: "batterycapacity"
    prettyName: "Battery capacity"
    isShown: true
  - name: "remainingruntime"
    prettyName: "Remaining runtime"
    isShown: true
  - name: "load"
    prettyName: "Load"
    isShown: true
  - name: "lineinteraction"
    prettyName: "Line interaction"
    isShown: true
  - name: "testresult"
    prettyName: "Test result"
    isShown: true
  - name: "lastpowerevent"
    prettyName: "Last power event"
    isShown: true
### end of the list of values

# Actions (only for read_only: false)
##
##
actions_list:
  - name: "Send an alert"
    on: 30
    exec: ""
  - name: "Shutdown host"
    on: 15
    exec: ""
